### ISSUE TITLE
CUDA trouble again...

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#30]
The current development branch does not build with CUDA 10.2; and definitely doesn't build with CUDA 11.3. In fact, even strf 0.12.2, which builds with CUDA 10.2, doesn't build 11.3.

... ah, well, it looks like strf now requires compilation in C++14 mode. I can see why you might want to require that, but cuda-kat is C++11. And the CUDA tests for strf using C++11 NVCC compilation. So, any chance of strf being made C++11-compatible again?

**Comment by robhz786** [comment]
Actually, strf always required C++14. This is stated in the README.md for a long time.
I didn't remember that cuda-kat is C++11. It was kind of luck that it worked all this time.

CUDA 11.3 works in my environment if I do the following:

    cmake -G Ninja \
        -DCMAKE_CUDA_FLAGS="-w"  \
        -DSTRF_BUILD_TESTS=ON \
        -DSTRF_BUILD_EXAMPLES=ON \
        -DSTRF_CUDA_SUPPORT=ON \
        -DCMAKE_CUDA_STANDARD=14 \
        -DCMAKE_BUILD_TYPE=Debug    str_root_source_directory
    cmake --build . && ctest

So, well, yes it requires C++14. But I will see if I can make it work with C++11 again.

I migrated to CUDA 11.3 because CUDA 10.2 doesn't support template variables. Actually, I think not even CUDA 11.0 works anymore.  

Anyway, I think strf 0.14 ( currently, the master branch ) still works with CUDA 10.2 in C++11.

**Comment by robhz786** [comment]
Fixed on release 0.15 ! 
Strf has been ported to C++11, and the compilations errors on NVCC 10.2 as well as on NVCC 11.x have been fixed.
I wasn't aware of many of the warnings because I was using the "-w" and "--expt-relaxed-constexpr" compile flag ( without knowing what they mean ). 
Thanks for pointing me out the failures!
