### ISSUE TITLE
Comments should indicate what a "CV string" is

### ISSUE THREAD

**Issue by eyalroz** [robhz786/strf#4]
There's a `cv_string.hpp` input type, and some use of this class and of `.cv()` members.

What does CV  mean in this context? Also, please document it in the code.

**Comment by robhz786** [comment]
`cv` and `sani` format functions are related to encoding conversion and sanitization. 
https://robhz786.github.io/strf/doc/quick_reference.html#encoding_conversion

**Comment by eyalroz** [comment]
The names are still rather confusing, and should at least have comments. After all, think about [`std::remove_cv`](https://en.cppreference.com/w/cpp/types/remove_cv).

**Comment by robhz786** [comment]
I will add the following comment on the top of  `cv_string.hpp:`

```
// cv and sani format functions are defined in no_cv_format_fn in string.hpp
// They are related to encoding conversion and sanitization.
```

**Comment by eyalroz** [comment]
I'd seriously consider using a more explicit name than "cv". Maybe "charset_converted" or something like that. And `strf::cv` could be an alias for that, for user convenience.

**Comment by robhz786** [comment]
But, for user convenience, the member function needs also to be short. Otherwise, the user would need type like: 
`std::to_string ( strf::right(u"an utf-16 string", 30, '-').charset_converted() );`

However, I see now that I should move the function to the end of `detail/format_functions.hpp`, where the other format function aliases are. That would make its purpose clearer. What do you think?

**Comment by eyalroz** [comment]
Well, what if you had:

```
    constexpr STRF_HD auto cv() const { return charset_converted(); }
    constexpr STRF_HD auto charset_converted() const { /* actual code here */ }
```
?

Or maybe have `cv` bw a [user-defined literal](https://en.cppreference.com/w/cpp/language/user_literal)?

**Comment by robhz786** [comment]
I renamed `cv` to `convert_charset`
